language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - FRAMEWORK_VERSION="5.0.*@dev" SKELETON_VERSION="dev-develop@dev"

before_install:
  - composer require illuminate/database:${FRAMEWORK_VERSION} laravel/laravel:${SKELETON_VERSION} --no-update

install: composer install --dev --prefer-dist

script: phpunit
